
language: node_js
node_js:
  - 8
  - 9

cache:
  directories:
    - 'node_modules'

install:
  - npm install

before_script:
  - node .travis/before.js

script:
  - node .travis/run.js
  - node app.js
