
language: node_js
node_js:
  - 8
  - 9

cache:
  directories:
    - 'node_modules'

install:
  - npm install

before_script:
  - node .travis/before.js

script:
  - node .travis/run.js
  - node app.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 30230918bab549fc19e9cb434f5190d3271f5914
  keep-history: true
  on:
    branch: master
  email: chenxiaowue1994@outlook.com
  name: travis build